baseURL: https://ehsandar.top
theme: PaperMod
title: "Amir Ehsandar"
languageCode: en
languageName: English
hasCJKLanguage: false
googleAnalytics: "G-G7S4PFDMT3"
copyright: ""
enableRobotsTXT: true
enableGitInfo: true
enableEmoji: true

params:
  defaultTheme: light
  disableThemeToggle: true
  gitRepo: https://github.com/ehsundar/ehsandar.com
  fingerprint: ""
  dateFormat: 2006-01-02
  author: Amir Ehsandar
  ShowPostNavLinks: true
  ShowCodeCopyButtons: true
  ShowToc: true
  hideFooter: true

  homeInfoParams:
    enabled: true
    title: Amir Ehsandar
    imageUrl: "profile.jpeg"
    imageTitle: my image

  socialIcons:
    - name: github
      title: GitHub
      url: "https://github.com/ehsundar"
    - name: X
      title: Twitter
      url: "https://twitter.com/ehsandot"
    - name: Telegram
      title: Telegram
      url: "https://t.me/ehsandaramir"

  editPost:
    URL: "https://github.com/ehsundar/ehsandar.com/tree/master/content"
    Text: "Edit this page"
    appendFilePath: true

ignoreErrors:
  - error-remote-getjson
  - error-missing-instagram-accesstoken

pagination:
  pagerSize: 20

menu:
  main:
    - weight: 1
      identifier: posts
      pre: ""
      post: ""
      name: Posts
      url: /posts/
      title: ""
    - weight: 2
      identifier: tags
      pre: ""
      post: ""
      name: Tags
      url: /tags/
      title: ""
    - weight: 3
      identifier: categories
      pre: ""
      post: ""
      name: Categories
      url: /categories/
      title: ""

outputs:
  home:
    - HTML
    - RSS
    - JSON

markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    noClasses: false
    anchorLineNos: true
    codeFences: true
    guessSyntax: true
    lineNos: true
    style: monokai
